apiVersion: apps/v1
kind: Deployment
metadata:
  name: netflix-clone-deployment
  labels:
    app: netflix-clone
spec:
  replicas: 2
  selector:
    matchLabels:
      app: netflix-clone
  template:
    metadata:
      labels:
        app: netflix-clone
    spec:
      imagePullSecrets:
      - name: my-docker-registry-secret
      containers:
      - name: netflix-clone
        image: tarunshori/netflix:latest
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "256Mi"
            cpu: "500m"
          limits:
            memory: "512Mi"
            cpu: "1"

---
apiVersion: v1
kind: Service
metadata:
  name: netflix-clone-service
spec:
  externalTrafficPolicy: Local
  type: NodePort  # Change this line from ClusterIP to NodePort
  selector:
    app: netflix-clone
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30001  # Specify the NodePort range (usually 30000-32767)
